package com.ecomm.inventory.api;

import java.util.List;

import com.ecomm.inventory.domain.Product;
import com.ecomm.inventory.domain.ProductSearch;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ecommerce
//  @ File Name : InventoryManager.java
//  @ Date : 11/4/2019
//  @ Author : 
//
//



/**
 * @author Adarsh
 *
 */
public interface InventoryManager {
	
	/**
	 * @param productSearch
	 * @return
	 */
	public List<Product> getProducts(ProductSearch productSearch) ;
	
	/**
	 * @param productId
	 * @return
	 */
	public Product getProductDetails(int productId);
	
	/**
	 * @param product
	 * @return
	 */
	public boolean addProduct(Product product);
	
	/**
	 * @param product
	 * @return
	 */
	public Product updateProduct(Product product);
	
}
