package com.ecomm.inventory.api;

import java.util.List;

import com.ecomm.inventory.domain.Product;
import com.ecomm.inventory.domain.ProductSearch;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ecommerce
//  @ File Name : InventoryManager.java
//  @ Date : 11/4/2019
//  @ Author : 
//
//




/** */
public interface InventoryManager {
	
	public List<Product> getProducts(ProductSearch productSearch) ;
	
	/** */
	public Product getProductDetails(int productId);
	
}
