package com.ecomm.inventory.service;

import java.util.List;

import com.ecomm.inventory.api.InventoryManager;
import com.ecomm.inventory.domain.Product;
import com.ecomm.inventory.domain.ProductSearch;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ecommerce
//  @ File Name : InventoryManagerImpl.java
//  @ Date : 11/4/2019
//  @ Author : 
//
//




/** */
public class InventoryManagerImpl implements InventoryManager{
	/** */
	public List<Product> getProducts(ProductSearch productSearch) {
		return null;
	}
	
	/** */
	public Product getProductDetails(int productId) {
		return null;
		
	}

	/* (non-Javadoc)
	 * @see com.ecomm.inventory.api.InventoryManager#addProduct(com.ecomm.inventory.domain.Product)
	 */
	public boolean addProduct(Product product) {
		// TODO Auto-generated method stub
		return false;
	}

	/* (non-Javadoc)
	 * @see com.ecomm.inventory.api.InventoryManager#updateProduct(com.ecomm.inventory.domain.Product)
	 */
	public Product updateProduct(Product product) {
		// TODO Auto-generated method stub
		return null;
	}
}
