package com.ecomm.inventory.domain;

import javax.persistence.Id;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ecommerce
//  @ File Name : ProductSearch.java
//  @ Date : 11/4/2019
//  @ Author : 
//
//




/** */
public class ProductSearch {
	/** */
	private int productId;
	
	/**
	 * @return the productId
	 */
	public int getProductId() {
		return productId;
	}

	/**
	 * @param productId the productId to set
	 */
	public void setProductId(int productId) {
		this.productId = productId;
	}

	/**
	 * @return the limit
	 */
	public Object getLimit() {
		return limit;
	}



	/**
	 * @return the offset
	 */
	public Object getOffset() {
		return offset;
	}



	/**
	 * @return the name
	 */
	public Object getName() {
		return name;
	}



	/**
	 * @param limit the limit to set
	 */
	public void setLimit(int limit) {
		this.limit = limit;
	}

	/**
	 * @param offset the offset to set
	 */
	public void setOffset(int offset) {
		this.offset = offset;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the category
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * @param category the category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/** */
	private int limit;
	
	/** */
	private int offset;
	
	/** */
	private String name;
	
	/** */
	private String category;
}
