package com.ecomm.inventory.domain;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ecommerce
//  @ File Name : Product.java
//  @ Date : 11/4/2019
//  @ Author : 
//
//




/** */
@Entity
@Table(name="ecommproduct")
public class Product {
	
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	@Id
	@Column(name="id")
	private Integer id;
	/** */
	@Column(name="name")
	private String name;
	
	/** */
	@Column(name="description")
	private String description;
	
	/** */
	@OneToMany
	@JoinColumn(name="id")
	@ElementCollection
	private List<Review> reviews;
	
	/** */
	//@Column(name="keyFeatures")
	//@OneToMany
	@JoinColumn(name="keyFeatures")
	@ElementCollection
	private Collection<String> keyFeatures;
	
	/** */
	//@Column(name="images")
	//@OneToMany
	@JoinColumn(name="images")
	@ElementCollection
	private Collection<String> images;
	
	/** */
	//@Column(name="categories")
	//@OneToMany
	@JoinColumn(name="categories")
	@ElementCollection
	private Collection<String> categories;
	
	/** */
	@Column(name="rating")
	 @Enumerated(EnumType.ORDINAL)
	private Rating rating;
	
	/** */
	@Column(name="price")
	private BigDecimal price;
	
	/** */
	@Column(name="discountpercent")
	private int discountPercent;
	
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the reviews
	 */
	public List<Review> getReviews() {
		return reviews;
	}

	/**
	 * @param reviews the reviews to set
	 */
	public void setReviews(List<Review> reviews) {
		this.reviews = reviews;
	}

	

	/**
	 * @return the keyFeatures
	 */
	public Collection<String> getKeyFeatures() {
		return keyFeatures;
	}

	/**
	 * @param keyFeatures the keyFeatures to set
	 */
	public void setKeyFeatures(Collection<String> keyFeatures) {
		this.keyFeatures = keyFeatures;
	}

	/**
	 * @return the images
	 */
	public Collection<String> getImages() {
		return images;
	}

	/**
	 * @param images the images to set
	 */
	public void setImages(Collection<String> images) {
		this.images = images;
	}

	/**
	 * @return the categories
	 */
	public Collection<String> getCategories() {
		return categories;
	}

	/**
	 * @param categories the categories to set
	 */
	public void setCategories(Collection<String> categories) {
		this.categories = categories;
	}

	/**
	 * @param tags the tags to set
	 */
	public void setTags(Collection<String> tags) {
		this.tags = tags;
	}

	/**
	 * @return the rating
	 */
	public Enum getRating() {
		return rating;
	}



	/**
	 * @return the price
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * @param rating the rating to set
	 */
	public void setRating(Rating rating) {
		this.rating = rating;
	}

	/**
	 * @param price the price to set
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * @return the discountPercent
	 */
	public int getDiscountPercent() {
		return discountPercent;
	}

	/**
	 * @param discountPercent the discountPercent to set
	 */
	public void setDiscountPercent(int discountPercent) {
		this.discountPercent = discountPercent;
	}

	
	/**
	 * @return the tags
	 */
	public Collection<String> getTags() {
		return tags;
	}

	/**
	 * @param tags the tags to set
	 */
	public void setTags(List<String> tags) {
		this.tags = tags;
	}

	/**
	 * @return the metaData
	 */
	public MetaData getMetaData() {
		return metaData;
	}

	/**
	 * @param metaData the metaData to set
	 */
	public void setMetaData(MetaData metaData) {
		this.metaData = metaData;
	}

	/** */
	//@OneToMany
	@JoinColumn(name="tags")
	@ElementCollection
	private Collection<String> tags;
	
	/** */
	@OneToOne
	@JoinColumn(name="metadata")
	private MetaData metaData;
}
