package com.ecomm.inventory.domain;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ecommerce
//  @ File Name : Rating.java
//  @ Date : 11/4/2019
//  @ Author : 
//
//




/** */
public enum Rating {
 VERY_BAD,BAD,GOOD, EXCELLENT;
}
