package com.ecomm.inventory.domain;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ecommerce
//  @ File Name : Review.java
//  @ Date : 11/4/2019
//  @ Author : 
//
//




/** */
public class Review {
	/**
	 * @return the rating
	 */
	public Rating getRating() {
		return rating;
	}

	/**
	 * @param rating the rating to set
	 */
	public void setRating(Rating rating) {
		this.rating = rating;
	}

	/**
	 * @return the comment
	 */
	public Comment getComment() {
		return comment;
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(Comment comment) {
		this.comment = comment;
	}

	/**
	 * @return the replyComments
	 */
	public List<Comment> getReplyComments() {
		return replyComments;
	}

	/**
	 * @param replyComments the replyComments to set
	 */
	public void setReplyComments(List<Comment> replyComments) {
		this.replyComments = replyComments;
	}

	/** */
	private Rating rating;
	
	/** */
	private Comment comment;
	
	/** */
	private List<Comment> replyComments;
}
